contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bencher channel"
    url: https://nfcore.slack.com/channels/bencher
    about: Discussion about the nf-core/bencher pipeline
